### ISSUE TITLE
bridgeboard not starting up on docker

### ISSUE THREAD

**Issue by digi-banana** [Woahai321/SeerrBridge#35]
I have this running on Docker. SeerrBridge works perfectly fine, but BridgeBoard gives me this error:

> bridgeboard@0.1.0 start
> next start --port 3777
sh: 1: next: not found

Within the .env file, I've run it both as headless_mode = true and false. I'm not sure what else would cause the issue since it's a straight pull from Docker.

**Comment by Woahai321** [comment]
I have just run a fresh ubuntu install and ran seerrbridge via docker, using the provided docker compose. No issues on my end.

I will need more detailed logs to troubleshoot.

Have you tried building the Docker image locally with the .local.yml file?

**Comment by andyhawks** [comment]
I encountered the same issue running from ghcr.io/woahai321/bridgeboard:latest on July 8. Building from docker-compose.local.yml worked for me.

**Comment by Woahai321** [comment]
@andyhawks, Glad building locally worked for you. Not sure why the image is throwing errors on your end. I have done a number of tests with new runs on both Windows and Linux in Docker, and even on new machines. Works no problem.

I will leave this open a little longer to see if there are any other reports on this issue.

**Comment by cyanidefv** [comment]
I am having this same issue

**Comment by SlappyBono** [comment]
I think the problem is this. In the README under Getting Started is following docker-compose.yml:
```
services:
  seerrbridge:
    image: ghcr.io/woahai321/seerrbridge:latest
    container_name: seerrbridge
    ports:
      - "8777:8777"
    env_file:
      - ./.env
    volumes:
      - shared_logs:/app
      - ./.env:/app/.env
    restart: unless-stopped
    command: >
      sh -c "
        cat /app/.env > /dev/null && 
        echo 'Starting SeerrBridge with refreshed env' &&
        uvicorn main:app --host 0.0.0.0 --port 8777
      "
    networks:
      - seerrbridge_network

  bridgeboard:
    image: ghcr.io/woahai321/bridgeboard:latest
    container_name: bridgeboard
    ports:
      - "3777:3777"
    env_file:
      - ./.env
    volumes:
      - shared_logs:/app
      - ./.env:/app/.env
    environment:
      - SEERRBRIDGE_URL=http://seerrbridge:8777
      - SEERRBRIDGE_LOG_PATH=/logs/seerrbridge.log
    entrypoint: >
      sh -c "
        npm start
      "
    restart: unless-stopped
    depends_on:
      - seerrbridge
    networks:
      - seerrbridge_network

volumes:
  shared_logs:

networks:
  seerrbridge_network:
    driver: bridge
```

In the project there is following docker-compose.yml:
```
services:
  seerrbridge:
    image: ghcr.io/woahai321/seerrbridge:latest
    container_name: seerrbridge
    ports:
      - "8777:8777"
    env_file:
      - ./.env
    volumes:
      - shared_logs:/app/logs
      - ./.env:/app/.env
    restart: unless-stopped
    command: >
      sh -c "
        cat /app/.env > /dev/null && 
        echo 'Starting SeerrBridge with refreshed env' &&
        uvicorn main:app --host 0.0.0.0 --port 8777
      "
    networks:
      - seerrbridge_network

  bridgeboard:
    image: ghcr.io/woahai321/bridgeboard:latest
    container_name: bridgeboard
    ports:
      - "3777:3777"
    env_file:
      - ./.env
    volumes:
      - shared_logs:/app/logs
      - ./.env:/app/.env
    environment:
      - SEERRBRIDGE_URL=http://seerrbridge:8777
      - SEERRBRIDGE_LOG_PATH=/logs/seerrbridge.log
    entrypoint: >
      sh -c "
        npm start
      "
    restart: unless-stopped
    depends_on:
      - seerrbridge
    networks:
      - seerrbridge_network

volumes:
  shared_logs:

networks:
  seerrbridge_network:
    driver: bridge
```

Under volumes für the shared_logs there is missing the /logs in the README. So when you are using the definition from the README as your docker-compose.yml it tries to overwrite the /app instead of mounting it to /logs and that's why you encouter this problem.
At least I ran into this.
